### ISSUE TITLE
What are the features?

### ISSUE THREAD

**Issue by SnooHD** [elrumordelaluz/svgson-next#3]
First of all, thank you for building this.
I am working on a SVG based app, and would be using this for the long run.
Can you perhaps highlight some specific changes / features in comparison to current stable svgson?

Thanks!

**Comment by elrumordelaluz** [comment]
hi @SnooHD,
So happy you found useful this _library_.

Sure, let me make a synthesis for you here asap. Will be probably a good starting point to improve _Documentation_.

**Comment by elrumordelaluz** [comment]
hi @SnooHD just wanted to let you know that updated the [Readme](https://github.com/elrumordelaluz/svgson-next/blob/master/README.md) with the current `API`.

Let me know if there is any issue related?

**Comment by elrumordelaluz** [comment]
Regarding this _Issue_, I think chatting with you I show you the difference in terms of _package_ weight and the simplifications of the API.

**Comment by SnooHD** [comment]
Thanks for updating it!
Yes i understand that this package is a lot more efficient :)
I will be implementing this now, thanks again! <3
