### ISSUE TITLE
Error in parsing SVG: Inappropriately located doctype declaration

### ISSUE THREAD

**Issue by riovir** [elrumordelaluz/svgson-next#5]
This issue comes from SVGO. To reproduce:
```JavaScript
const svg = `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 32 32">
<path class="st0" d="M16,16v15.5c0,0,9.3-2.6,12.7-15.5H16z"/>
</svg>`;
svgson(svg, { optimize: true, svgoConfig: { plugins: [] } }).catch(err => console.log(err));
```

As far as I can see this line is the culprit: https://github.com/elrumordelaluz/svgson-next/blob/master/src/tools.js#L38

When I manually created an SVG file with `<root>` wrapped around it, SVGO blew up on the doctype declaration not being top level.

**Comment by riovir** [comment]
I now realize that this issue collides with your use case of supporting multiple SVGs in a string (I think). I can work around the problem by disabling SVG optimization on `svgson-next` and simply feeding a pre-optimized string into into it.

**Comment by elrumordelaluz** [comment]
@riovir please give it a try with `v3.0.1`
